<?php 
namespace App\http\Controllers;

trait info {
  public static function countriesCodes () {
    return  ["United Kingdom"=> "44" , "United States of America"=> "1" , "Algeria"=> "213" , "Andorra"=> "376" , "Angola"=> "244" , "Anguilla"=> "1264" , "Antigua & Barbuda"=> "1268" , "Argentina"=> "54" , "Armenia"=> "374" , "Aruba"=> "297" , "Australia"=> "61" , "Austria"=> "43" , "Azerbaijan"=> "994" , "Bahamas"=> "1242" , "Bahrain"=> "973" , "Bangladesh"=> "880" , "Barbados"=> "1246" , "Belarus"=> "375" , "Belgium"=> "32" , "Belize"=> "501" , "Benin"=> "229" , "Bermuda"=> "1441" , "Bhutan"=> "975" , "Bolivia"=> "591" , "Bosnia Herzegovina"=> "387" , "Botswana"=> "267" , "Brazil"=> "55" , "Brunei"=> "673" , "Bulgaria"=> "359" , "Burkina Faso"=> "226" , "Burundi"=> "257" , "Cambodia"=> "855" , "Cameroon"=> "237" , "Canada"=> "1" , "Cape Verde Islands"=> "238" , "Cayman Islands"=> "1345" , "Central African Republic"=> "236" , "Chile"=> "56" , "China"=> "86" , "Colombia"=> "57" , "Comoros"=> "269" , "Congo"=> "242" , "Cook Islands"=> "682" , "Costa Rica"=> "506" , "Croatia"=> "385" , "Cuba"=> "53" , "Cyprus North"=> "90392" , "Cyprus South"=> "357" , "Czech Republic"=> "42" , "Denmark"=> "45" , "Djibouti"=> "253" , "Dominica"=> "1809" , "Dominican Republic"=> "1809" , "Ecuador"=> "593" , "Egypt"=> "20" , "El Salvador"=> "503" , "Equatorial Guinea"=> "240" , "Eritrea"=> "291" , "Estonia"=> "372" , "Ethiopia"=> "251" , "Falkland Islands"=> "500" , "Faroe Islands"=> "298" , "Fiji"=> "679" , "Finland"=> "358" , "France"=> "33" , "French Guiana"=> "594" , "French Polynesia"=> "689" , "Gabon"=> "241" , "Gambia"=> "220" , "Georgia"=> "7880" , "Germany"=> "49" , "Ghana"=> "233" , "Gibraltar"=> "350" , "Greece"=> "30" , "Greenland"=> "299" , "Grenada"=> "1473" , "Guadeloupe"=> "590" , "Guam"=> "671" , "Guatemala"=> "502" , "Guinea"=> "224" , "Guinea - Bissau"=> "245" , "Guyana"=> "592" , "Haiti"=> "509" , "Honduras"=> "504" , "Hong Kong"=> "852" , "Hungary"=> "36" , "Iceland"=> "354" , "India"=> "91" , "Indonesia"=> "62" , "Iran"=> "98" , "Iraq"=> "964" , "Ireland"=> "353" , "Israel"=> "972" , "Italy"=> "39" , "Jamaica"=> "1876" , "Japan"=> "81" , "Jordan"=> "962" , "Kazakhstan"=> "7" , "Kenya"=> "254" , "Kiribati"=> "686" , "Korea North"=> "850" , "Korea South"=> "82" , "Kuwait"=> "965" , "Kyrgyzstan"=> "996" , "Laos"=> "856" , "Latvia"=> "371" , "Lebanon"=> "961" , "Lesotho"=> "266" , "Liberia"=> "231" , "Libya"=> "218" , "Liechtenstein"=> "417" , "Lithuania"=> "370" , "Luxembourg"=> "352" , "Macao"=> "853" , "Macedonia"=> "389" , "Madagascar"=> "261" , "Malawi"=> "265" , "Malaysia"=> "60" , "Maldives"=> "960" , "Mali"=> "223" , "Malta"=> "356" , "Marshall Islands"=> "692" , "Martinique"=> "596" , "Mauritania"=> "222" , "Mayotte"=> "269" , "Mexico"=> "52" , "Micronesia"=> "691" , "Moldova"=> "373" , "Monaco"=> "377" , "Mongolia"=> "976" , "Montserrat"=> "1664" , "Morocco"=> "212" , "Mozambique"=> "258" , "Myanmar"=> "95" , "Namibia"=> "264" , "Nauru"=> "674" , "Nepal"=> "977" , "Netherlands"=> "31" , "New Caledonia"=> "687" , "New Zealand"=> "64" , "Nicaragua"=> "505" , "Niger"=> "227" , "Nigeria"=> "234" , "Niue"=> "683" , "Norfolk Islands"=> "672" , "Northern Marianas"=> "670" , "Norway"=> "47" , "Oman"=> "968" , "Palau"=> "680" , "Panama"=> "507" , "Papua New Guinea"=> "675" , "Paraguay"=> "595" , "Peru"=> "51" , "Philippines"=> "63" , "Poland"=> "48" , "Portugal"=> "351" , "Puerto Rico"=> "1787" , "Qatar"=> "974" , "Reunion"=> "262" , "Romania"=> "40" , "Russia"=> "7" , "Rwanda"=> "250" , "San Marino"=> "378" , "Sao Tome & Principe"=> "239" , "Saudi Arabia"=> "966" , "Senegal"=> "221" , "Serbia"=> "381" , "Seychelles"=> "248" , "Sierra Leone"=> "232" , "Singapore"=> "65" , "Slovak Republic"=> "421" , "Slovenia"=> "386" , "Solomon Islands"=> "677" , "Somalia"=> "252" , "South Africa"=> "27" , "Spain"=> "34" , "Sri Lanka"=> "94" , "St. Helena"=> "290" , "St. Kitts"=> "1869" , "St. Lucia"=> "1758" , "Sudan"=> "249" , "Suriname"=> "597" , "Swaziland"=> "268" , "Sweden"=> "46" , "Switzerland"=> "41" , "Syria"=> "963" , "Taiwan"=> "886" , "Tajikstan"=> "7" , "Thailand"=> "66" , "Togo"=> "228" , "Tonga"=> "676" , "Trinidad & Tobago"=> "1868" , "Tunisia"=> "216" , "Turkey"=> "90" , "Turkmenistan"=> "7" , "Turkmenistan"=> "993" , "Turks & Caicos Islands"=> "1649" , "Tuvalu"=> "688" , "Uganda"=> "256" , "Ukraine"=> "380" , "United Arab Emirates"=> "971" , "Uruguay"=> "598" , "Uzbekistan"=> "7" , "Vanuatu"=> "678" , "Vatican City"=> "379" , "Venezuela"=> "58" , "Vietnam"=> "84" , "Virgin Islands - British"=> "1284" , "Virgin Islands - US"=> "1340" , "Wallis & Futuna"=> "681" , "Yemen - North"=> "969", "Yemen - South"=> "967" , "Zambia"=> "260" , "Zimbabwe"=> "263" , ];
  }

  public function infoof () {
//   $latinCountries = [
    
// ['e_name' => 'Afghanistan', 'code' => '93', 'iso' => 'AF'],
// ['e_name' => 'Albania', 'code' => '355', 'iso' => 'AL'],
// ['e_name' => 'Algeria', 'code' => '213', 'iso' => 'DZ'],
// ['e_name' => 'American Samoa', 'code' => '1-684', 'iso' => 'AS'],
// ['e_name' => 'Andorra', 'code' => '376', 'iso' => 'AD'],
// ['e_name' => 'Angola', 'code' => '244', 'iso' => 'AO'],
// ['e_name' => 'Anguilla', 'code' => '1-264', 'iso' => 'AI'],
// ['e_name' => 'Antarctica', 'code' => '672', 'iso' => 'AQ'],
// ['e_name' => 'Antigua and Barbuda', 'code' => '1-268', 'iso' => 'AG'],
// ['e_name' => 'Argentina', 'code' => '54', 'iso' => 'AR'],
// ['e_name' => 'Armenia', 'code' => '374', 'iso' => 'AM'],
// ['e_name' => 'Aruba', 'code' => '297', 'iso' => 'AW'],
// ['e_name' => 'Australia', 'code' => '61', 'iso' => 'AU'],
// ['e_name' => 'Austria', 'code' => '43', 'iso' => 'AT'],
// ['e_name' => 'Azerbaijan', 'code' => '994', 'iso' => 'AZ'],
// ['e_name' => 'Bahamas', 'code' => '1-242', 'iso' => 'BS'],
// ['e_name' => 'Bahrain', 'code' => '973', 'iso' => 'BH'],
// ['e_name' => 'Bangladesh', 'code' => '880', 'iso' => 'BD'],
// ['e_name' => 'Barbados', 'code' => '1-246', 'iso' => 'BB'],
// ['e_name' => 'Belarus', 'code' => '375', 'iso' => 'BY'],
// ['e_name' => 'Belgium', 'code' => '32', 'iso' => 'BE'],
// ['e_name' => 'Belize', 'code' => '501', 'iso' => 'BZ'],
// ['e_name' => 'Benin', 'code' => '229', 'iso' => 'BJ'],
// ['e_name' => 'Bermuda', 'code' => '1-441', 'iso' => 'BM'],
// ['e_name' => 'Bhutan', 'code' => '975', 'iso' => 'BT'],
// ['e_name' => 'Bolivia', 'code' => '591', 'iso' => 'BO'],
// ['e_name' => 'Bosnia and Herzegovina', 'code' => '387', 'iso' => 'BA'],
// ['e_name' => 'Botswana', 'code' => '267', 'iso' => 'BW'],
// ['e_name' => 'Brazil', 'code' => '55', 'iso' => 'BR'],
// ['e_name' => 'British Indian Ocean Territory', 'code' => '246', 'iso' => 'IO'],
// ['e_name' => 'British Virgin Islands', 'code' => '1-284', 'iso' => 'VG'],
// ['e_name' => 'Brunei', 'code' => '673', 'iso' => 'BN'],
// ['e_name' => 'Bulgaria', 'code' => '359', 'iso' => 'BG'],
// ['e_name' => 'Burkina Faso', 'code' => '226', 'iso' => 'BF'],
// ['e_name' => 'Burundi', 'code' => '257', 'iso' => 'BI'],
// ['e_name' => 'Cambodia', 'code' => '855', 'iso' => 'KH'],
// ['e_name' => 'Cameroon', 'code' => '237', 'iso' => 'CM'],
// ['e_name' => 'Canada', 'code' => '1', 'iso' => 'CA'],
// ['e_name' => 'Cape Verde', 'code' => '238', 'iso' => 'CV'],
// ['e_name' => 'Cayman Islands', 'code' => '1-345', 'iso' => 'KY'],
// ['e_name' => 'Central African Republic', 'code' => '236', 'iso' => 'CF'],
// ['e_name' => 'Chad', 'code' => '235', 'iso' => 'TD'],
// ['e_name' => 'Chile', 'code' => '56', 'iso' => 'CL'],
// ['e_name' => 'China', 'code' => '86', 'iso' => 'CN'],
// ['e_name' => 'Christmas Island', 'code' => '61', 'iso' => 'CX'],
// ['e_name' => 'Cocos Islands', 'code' => '61', 'iso' => 'CC'],
// ['e_name' => 'Colombia', 'code' => '57', 'iso' => 'CO'],
// ['e_name' => 'Comoros', 'code' => '269', 'iso' => 'KM'],
// ['e_name' => 'Cook Islands', 'code' => '682', 'iso' => 'CK'],
// ['e_name' => 'Costa Rica', 'code' => '506', 'iso' => 'CR'],
// ['e_name' => 'Croatia', 'code' => '385', 'iso' => 'HR'],
// ['e_name' => 'Cuba', 'code' => '53', 'iso' => 'CU'],
// ['e_name' => 'Curacao', 'code' => '599', 'iso' => 'CW'],
// ['e_name' => 'Cyprus', 'code' => '357', 'iso' => 'CY'],
// ['e_name' => 'Czech Republic', 'code' => '420', 'iso' => 'CZ'],
// ['e_name' => 'Democratic Republic of the Congo', 'code' => '243', 'iso' => 'CD'],
// ['e_name' => 'Denmark', 'code' => '45', 'iso' => 'DK'],
// ['e_name' => 'Djibouti', 'code' => '253', 'iso' => 'DJ'],
// ['e_name' => 'Dominica', 'code' => '1-767', 'iso' => 'DM'],
// ['e_name' => 'Dominican Republic', 'code' => '1-809, 1-829, 1-849', 'iso' => 'DO'],
// ['e_name' => 'East Timor', 'code' => '670', 'iso' => 'TL'],
// ['e_name' => 'Ecuador', 'code' => '593', 'iso' => 'EC'],
// ['e_name' => 'Egypt', 'code' => '20', 'iso' => 'EG'],
// ['e_name' => 'El Salvador', 'code' => '503', 'iso' => 'SV'],
// ['e_name' => 'Equatorial Guinea', 'code' => '240', 'iso' => 'GQ'],
// ['e_name' => 'Eritrea', 'code' => '291', 'iso' => 'ER'],
// ['e_name' => 'Estonia', 'code' => '372', 'iso' => 'EE'],
// ['e_name' => 'Ethiopia', 'code' => '251', 'iso' => 'ET'],
// ['e_name' => 'Falkland Islands', 'code' => '500', 'iso' => 'FK'],
// ['e_name' => 'Faroe Islands', 'code' => '298', 'iso' => 'FO'],
// ['e_name' => 'Fiji', 'code' => '679', 'iso' => 'FJ'],
// ['e_name' => 'Finland', 'code' => '358', 'iso' => 'FI'],
// ['e_name' => 'France', 'code' => '33', 'iso' => 'FR'],
// ['e_name' => 'French Polynesia', 'code' => '689', 'iso' => 'PF'],
// ['e_name' => 'Gabon', 'code' => '241', 'iso' => 'GA'],
// ['e_name' => 'Gambia', 'code' => '220', 'iso' => 'GM'],
// ['e_name' => 'Georgia', 'code' => '995', 'iso' => 'GE'],
// ['e_name' => 'Germany', 'code' => '49', 'iso' => 'DE'],
// ['e_name' => 'Ghana', 'code' => '233', 'iso' => 'GH'],
// ['e_name' => 'Gibraltar', 'code' => '350', 'iso' => 'GI'],
// ['e_name' => 'Greece', 'code' => '30', 'iso' => 'GR'],
// ['e_name' => 'Greenland', 'code' => '299', 'iso' => 'GL'],
// ['e_name' => 'Grenada', 'code' => '1-473', 'iso' => 'GD'],
// ['e_name' => 'Guam', 'code' => '1-671', 'iso' => 'GU'],
// ['e_name' => 'Guatemala', 'code' => '502', 'iso' => 'GT'],
// ['e_name' => 'Guernsey', 'code' => '44-1481', 'iso' => 'GG'],
// ['e_name' => 'Guinea', 'code' => '224', 'iso' => 'GN'],
// ['e_name' => 'Guinea-Bissau', 'code' => '245', 'iso' => 'GW'],
// ['e_name' => 'Guyana', 'code' => '592', 'iso' => 'GY'],
// ['e_name' => 'Haiti', 'code' => '509', 'iso' => 'HT'],
// ['e_name' => 'Honduras', 'code' => '504', 'iso' => 'HN'],
// ['e_name' => 'Hong Kong', 'code' => '852', 'iso' => 'HK'],
// ['e_name' => 'Hungary', 'code' => '36', 'iso' => 'HU'],
// ['e_name' => 'Iceland', 'code' => '354', 'iso' => 'IS'],
// ['e_name' => 'India', 'code' => '91', 'iso' => 'IN'],
// ['e_name' => 'Indonesia', 'code' => '62', 'iso' => 'ID'],
// ['e_name' => 'Iran', 'code' => '98', 'iso' => 'IR'],
// ['e_name' => 'Iraq', 'code' => '964', 'iso' => 'IQ'],
// ['e_name' => 'Ireland', 'code' => '353', 'iso' => 'IE'],
// ['e_name' => 'Isle of Man', 'code' => '44-1624', 'iso' => 'IM'],
// ['e_name' => 'Israel', 'code' => '972', 'iso' => 'IL'],
// ['e_name' => 'Italy', 'code' => '39', 'iso' => 'IT'],
// ['e_name' => 'Ivory Coast', 'code' => '225', 'iso' => 'CI'],
// ['e_name' => 'Jamaica', 'code' => '1-876', 'iso' => 'JM'],
// ['e_name' => 'Japan', 'code' => '81', 'iso' => 'JP'],
// ['e_name' => 'Jersey', 'code' => '44-1534', 'iso' => 'JE'],
// ['e_name' => 'Jordan', 'code' => '962', 'iso' => 'JO'],
// ['e_name' => 'Kazakhstan', 'code' => '7', 'iso' => 'KZ'],
// ['e_name' => 'Kenya', 'code' => '254', 'iso' => 'KE'],
// ['e_name' => 'Kiribati', 'code' => '686', 'iso' => 'KI'],
// ['e_name' => 'Kosovo', 'code' => '383', 'iso' => 'XK'],
// ['e_name' => 'Kuwait', 'code' => '965', 'iso' => 'KW'],
// ['e_name' => 'Kyrgyzstan', 'code' => '996', 'iso' => 'KG'],
// ['e_name' => 'Laos', 'code' => '856', 'iso' => 'LA'],
// ['e_name' => 'Latvia', 'code' => '371', 'iso' => 'LV'],
// ['e_name' => 'Lebanon', 'code' => '961', 'iso' => 'LB'],
// ['e_name' => 'Lesotho', 'code' => '266', 'iso' => 'LS'],
// ['e_name' => 'Liberia', 'code' => '231', 'iso' => 'LR'],
// ['e_name' => 'Libya', 'code' => '218', 'iso' => 'LY'],
// ['e_name' => 'Liechtenstein', 'code' => '423', 'iso' => 'LI'],
// ['e_name' => 'Lithuania', 'code' => '370', 'iso' => 'LT'],
// ['e_name' => 'Luxembourg', 'code' => '352', 'iso' => 'LU'],
// ['e_name' => 'Macao', 'code' => '853', 'iso' => 'MO'],
// ['e_name' => 'Macedonia', 'code' => '389', 'iso' => 'MK'],
// ['e_name' => 'Madagascar', 'code' => '261', 'iso' => 'MG'],
// ['e_name' => 'Malawi', 'code' => '265', 'iso' => 'MW'],
// ['e_name' => 'Malaysia', 'code' => '60', 'iso' => 'MY'],
// ['e_name' => 'Maldives', 'code' => '960', 'iso' => 'MV'],
// ['e_name' => 'Mali', 'code' => '223', 'iso' => 'ML'],
// ['e_name' => 'Malta', 'code' => '356', 'iso' => 'MT'],
// ['e_name' => 'Marshall Islands', 'code' => '692', 'iso' => 'MH'],
// ['e_name' => 'Mauritania', 'code' => '222', 'iso' => 'MR'],
// ['e_name' => 'Mauritius', 'code' => '230', 'iso' => 'MU'],
// ['e_name' => 'Mayotte', 'code' => '262', 'iso' => 'YT'],
// ['e_name' => 'Mexico', 'code' => '52', 'iso' => 'MX'],
// ['e_name' => 'Micronesia', 'code' => '691', 'iso' => 'FM'],
// ['e_name' => 'Moldova', 'code' => '373', 'iso' => 'MD'],
// ['e_name' => 'Monaco', 'code' => '377', 'iso' => 'MC'],
// ['e_name' => 'Mongolia', 'code' => '976', 'iso' => 'MN'],
// ['e_name' => 'Montenegro', 'code' => '382', 'iso' => 'ME'],
// ['e_name' => 'Montserrat', 'code' => '1-664', 'iso' => 'MS'],
// ['e_name' => 'Morocco', 'code' => '212', 'iso' => 'MA'],
// ['e_name' => 'Mozambique', 'code' => '258', 'iso' => 'MZ'],
// ['e_name' => 'Myanmar', 'code' => '95', 'iso' => 'MM'],
// ['e_name' => 'Namibia', 'code' => '264', 'iso' => 'NA'],
// ['e_name' => 'Nauru', 'code' => '674', 'iso' => 'NR'],
// ['e_name' => 'Nepal', 'code' => '977', 'iso' => 'NP'],
// ['e_name' => 'Netherlands', 'code' => '31', 'iso' => 'NL'],
// ['e_name' => 'Netherlands Antilles', 'code' => '599', 'iso' => 'AN'],
// ['e_name' => 'New Caledonia', 'code' => '687', 'iso' => 'NC'],
// ['e_name' => 'New Zealand', 'code' => '64', 'iso' => 'NZ'],
// ['e_name' => 'Nicaragua', 'code' => '505', 'iso' => 'NI'],
// ['e_name' => 'Niger', 'code' => '227', 'iso' => 'NE'],
// ['e_name' => 'Nigeria', 'code' => '234', 'iso' => 'NG'],
// ['e_name' => 'Niue', 'code' => '683', 'iso' => 'NU'],
// ['e_name' => 'North Korea', 'code' => '850', 'iso' => 'KP'],
// ['e_name' => 'Northern Mariana Islands', 'code' => '1-670', 'iso' => 'MP'],
// ['e_name' => 'Norway', 'code' => '47', 'iso' => 'NO'],
// ['e_name' => 'Oman', 'code' => '968', 'iso' => 'OM'],
// ['e_name' => 'Pakistan', 'code' => '92', 'iso' => 'PK'],
// ['e_name' => 'Palau', 'code' => '680', 'iso' => 'PW'],
// ['e_name' => 'Palestine', 'code' => '970', 'iso' => 'PS'],
// ['e_name' => 'Panama', 'code' => '507', 'iso' => 'PA'],
// ['e_name' => 'Papua New Guinea', 'code' => '675', 'iso' => 'PG'],
// ['e_name' => 'Paraguay', 'code' => '595', 'iso' => 'PY'],
// ['e_name' => 'Peru', 'code' => '51', 'iso' => 'PE'],
// ['e_name' => 'Philippines', 'code' => '63', 'iso' => 'PH'],
// ['e_name' => 'Pitcairn', 'code' => '64', 'iso' => 'PN'],
// ['e_name' => 'Poland', 'code' => '48', 'iso' => 'PL'],
// ['e_name' => 'Portugal', 'code' => '351', 'iso' => 'PT'],
// ['e_name' => 'Puerto Rico', 'code' => '1-787, 1-939', 'iso' => 'PR'],
// ['e_name' => 'Qatar', 'code' => '974', 'iso' => 'QA'],
// ['e_name' => 'Republic of the Congo', 'code' => '242', 'iso' => 'CG'],
// ['e_name' => 'Reunion', 'code' => '262', 'iso' => 'RE'],
// ['e_name' => 'Romania', 'code' => '40', 'iso' => 'RO'],
// ['e_name' => 'Russia', 'code' => '7', 'iso' => 'RU'],
// ['e_name' => 'Rwanda', 'code' => '250', 'iso' => 'RW'],
// ['e_name' => 'Saint Barthelemy', 'code' => '590', 'iso' => 'BL'],
// ['e_name' => 'Saint Helena', 'code' => '290', 'iso' => 'SH'],
// ['e_name' => 'Saint Kitts and Nevis', 'code' => '1-869', 'iso' => 'KN'],
// ['e_name' => 'Saint Lucia', 'code' => '1-758', 'iso' => 'LC'],
// ['e_name' => 'Saint Martin', 'code' => '590', 'iso' => 'MF'],
// ['e_name' => 'Saint Pierre and Miquelon', 'code' => '508', 'iso' => 'PM'],
// ['e_name' => 'Saint Vincent and the Grenadines', 'code' => '1-784', 'iso' => 'VC'],
// ['e_name' => 'Samoa', 'code' => '685', 'iso' => 'WS'],
// ['e_name' => 'San Marino', 'code' => '378', 'iso' => 'SM'],
// ['e_name' => 'Sao Tome and Principe', 'code' => '239', 'iso' => 'ST'],
// ['e_name' => 'Saudi Arabia', 'code' => '966', 'iso' => 'SA'],
// ['e_name' => 'Senegal', 'code' => '221', 'iso' => 'SN'],
// ['e_name' => 'Serbia', 'code' => '381', 'iso' => 'RS'],
// ['e_name' => 'Seychelles', 'code' => '248', 'iso' => 'SC'],
// ['e_name' => 'Sierra Leone', 'code' => '232', 'iso' => 'SL'],
// ['e_name' => 'Singapore', 'code' => '65', 'iso' => 'SG'],
// ['e_name' => 'Sint Maarten', 'code' => '1-721', 'iso' => 'SX'],
// ['e_name' => 'Slovakia', 'code' => '421', 'iso' => 'SK'],
// ['e_name' => 'Slovenia', 'code' => '386', 'iso' => 'SI'],
// ['e_name' => 'Solomon Islands', 'code' => '677', 'iso' => 'SB'],
// ['e_name' => 'Somalia', 'code' => '252', 'iso' => 'SO'],
// ['e_name' => 'South Africa', 'code' => '27', 'iso' => 'ZA'],
// ['e_name' => 'South Korea', 'code' => '82', 'iso' => 'KR'],
// ['e_name' => 'South Sudan', 'code' => '211', 'iso' => 'SS'],
// ['e_name' => 'Spain', 'code' => '34', 'iso' => 'ES'],
// ['e_name' => 'Sri Lanka', 'code' => '94', 'iso' => 'LK'],
// ['e_name' => 'Sudan', 'code' => '249', 'iso' => 'SD'],
// ['e_name' => 'Suriname', 'code' => '597', 'iso' => 'SR'],
// ['e_name' => 'Svalbard and Jan Mayen', 'code' => '47', 'iso' => 'SJ'],
// ['e_name' => 'Swaziland', 'code' => '268', 'iso' => 'SZ'],
// ['e_name' => 'Sweden', 'code' => '46', 'iso' => 'SE'],
// ['e_name' => 'Switzerland', 'code' => '41', 'iso' => 'CH'],
// ['e_name' => 'Syria', 'code' => '963', 'iso' => 'SY'],
// ['e_name' => 'Taiwan', 'code' => '886', 'iso' => 'TW'],
// ['e_name' => 'Tajikistan', 'code' => '992', 'iso' => 'TJ'],
// ['e_name' => 'Tanzania', 'code' => '255', 'iso' => 'TZ'],
// ['e_name' => 'Thailand', 'code' => '66', 'iso' => 'TH'],
// ['e_name' => 'Togo', 'code' => '228', 'iso' => 'TG'],
// ['e_name' => 'Tokelau', 'code' => '690', 'iso' => 'TK'],
// ['e_name' => 'Tonga', 'code' => '676', 'iso' => 'TO'],
// ['e_name' => 'Trinidad and Tobago', 'code' => '1-868', 'iso' => 'TT'],
// ['e_name' => 'Tunisia', 'code' => '216', 'iso' => 'TN'],
// ['e_name' => 'Turkey', 'code' => '90', 'iso' => 'TR'],
// ['e_name' => 'Turkmenistan', 'code' => '993', 'iso' => 'TM'],
// ['e_name' => 'Turks and Caicos Islands', 'code' => '1-649', 'iso' => 'TC'],
// ['e_name' => 'Tuvalu', 'code' => '688', 'iso' => 'TV'],
// ['e_name' => 'U.S. Virgin Islands', 'code' => '1-340', 'iso' => 'VI'],
// ['e_name' => 'Uganda', 'code' => '256', 'iso' => 'UG'],
// ['e_name' => 'Ukraine', 'code' => '380', 'iso' => 'UA'],
// ['e_name' => 'United Arab Emirates', 'code' => '971', 'iso' => 'AE'],
// ['e_name' => 'United Kingdom', 'code' => '44', 'iso' => 'GB'],
// ['e_name' => 'United States', 'code' => '1', 'iso' => 'US'],
// ['e_name' => 'Uruguay', 'code' => '598', 'iso' => 'UY'],
// ['e_name' => 'Uzbekistan', 'code' => '998', 'iso' => 'UZ'],
// ['e_name' => 'Vanuatu', 'code' => '678', 'iso' => 'VU'],
// ['e_name' => 'Vatican', 'code' => '379', 'iso' => 'VA'],
// ['e_name' => 'Venezuela', 'code' => '58', 'iso' => 'VE'],
// ['e_name' => 'Vietnam', 'code' => '84', 'iso' => 'VN'],
// ['e_name' => 'Wallis and Futuna', 'code' => '681', 'iso' => 'WF'],
// ['e_name' => 'Western Sahara', 'code' => '212', 'iso' => 'EH'],
// ['e_name' => 'Yemen', 'code' => '967', 'iso' => 'YE'],
// ['e_name' => 'Zambia', 'code' => '260', 'iso' => 'ZM'],
// ['e_name' => 'Zimbabwe', 'code' => '263', 'iso' => 'ZW']
//     ];

// $countries = [
//   "ET" => "أثيوبيا",
//   "AZ" => "أذربيجان",
//   "AM" => "أرمينيا",
//   "AW" => "أروبا",
//   "ER" => "إريتريا",
//   "ES" => "إسبانيا",
//   "AU" => "أستراليا",
//   "EE" => "استونيا",
//   "AF" => "أفغانستان",
//   "IO" => "إقليم المحيط الهندي البريطاني",
//   "RU" => "الاتحاد الروسي",
//   "TF" => "الأراضي الفرنسية الجنوبية والقارة القطبية الجنوبية",
//   "AR" => "الأرجنتين",
//   "JO" => "الأردن",
//   "EC" => "الإكوادور",
//   "AE" => "الإمارات العربية المتحدة",
//   "AL" => "ألبانيا",
//   "BH" => "البحرين",
//   "BR" => "البرازيل",
//   "PT" => "البرتغال",
//   "BA" => "البوسنة والهرسك",
//   "GA" => "الجابون",
//   "ME" => "الجبل الأسود",
//   "DZ" => "الجزائر",
//   "CZ" => "الجمهورية التشيكية",
//   "DK" => "الدنمرك",
//   "CV" => "الرأس الأخضر",
//   "SV" => "السلفادور",
//   "SN" => "السنغال",
//   "SD" => "السودان",
//   "SE" => "السويد",
//   "EH" => "الصحراء الغربية",
//   "SO" => "الصومال",
//   "CN" => "الصين",
//   "IQ" => "العراق",
//   "PH" => "الفلبين",
//   "AQ" => "القارة القطبية الجنوبية",
//   "CM" => "الكاميرون",
//   "VA" => "الكرسي الرسولي (الفاتيكان)",
//   "KW" => "الكويت",
//   "MQ" => "المارتينيك",
//   "DE" => "ألمانيا",
//   "HU" => "المجر",
//   "MX" => "المكسيك",
//   "SA" => "المملكة العربية السعودية",
//   "UK" => "المملكة المتحدة",
//   "NO" => "النرويج",
//   "AT" => "النمسا",
//   "NE" => "النيجر",
//   "JP" => "اليابان",
//   "YE" => "اليمن",
//   "GR" => "اليونان",
//   "AG" => "انتيغوا وبربودا",
//   "AO" => "أنجولا",
//   "AD" => "أندورا",
//   "ID" => "إندونيسيا",
//   "AI" => "أنغيلا",
//   "UY" => "أوروجواي",
//   "UZ" => "أوزبكستان",
//   "UG" => "أوغندا",
//   "UA" => "أوكرانيا",
//   "IR"   => "إيران",
//   "IE" => "ايرلندا",
//   "IS" => "أيسلندا",
//   "IT" => "إيطاليا",
//   "PG" => "بابوا غينيا الجديدة",
//   "PY" => "باراغواي",
//   "PK" => "باكستان",
//   "PW" => "بالاو",
//   "BB" => "بربادوس",
//   "BM" => "برمودا",
//   "BN" => "بروناي دار السلام",
//   "BE" => "بلجيكا",
//   "BG" => "بلغاريا",
//   "BZ" => "بليز",
//   "BD" => "بنغلاديش",
//   "PA" => "بنما",
//   "BJ" => "بنين",
//   "BT" => "بوتان",
//   "BW" => "بوتسوانا",
//   "BF" => "بوركينا فاسو",
//   "MM" => "بورما",
//   "BI" => "بوروندي",
//   "PL" => "بولندا",
//   "BO" => "بوليفيا",
//   "PF" => "بولينيزيا الفرنسية",
//   "BQ" => "بونير",
//   "PR" => "بويرتو ريكو",
//   "PE" => "بيرو",
//   "TH" => "تايلاند",
//   "TW" => "تايوان",
//   "TM" => "تركمانستان",
//   "TR" => "تركيا",
//   "TT" => "ترينيداد وتوباجو",
//   "TD" => "تشاد",
//   "CL" => "تشيلي",
//   "TZ" => "تنزانيا",
//   "TG" => "توجو",
//   "TV" => "توفالو",
//   "TK" => "توكيلاو",
//   "TO" => "تونجا",
//   "TN" => "تونس",
//   "TL" => "تيمور الشرقية",
//   "JM" => "جامايكا",
//   "GM" => "جامبيا",
//   "GI" => "جبل طارق",
//   "GD" => "جرينادا",
//   "GL" => "جرينلند",
//   "AN" => "جزر الانتيل الهولندية",
//   "BS" => "جزر البهاما",
//   "KM" => "جزر القمر",
//   "MV" => "جزر المالديف",
//   "UM" => "جزر الولايات المتحدة البعيدة الصغيرة",
//   "PN" => "جزر بيتكيرن",
//   "TC" => "جزر تركس وكايكوس",
//   "SB" => "جزر سليمان",
//   "FO" => "جزر فارو",
//   "FK" => "جزر فوكلاند (مالفيناس)",
//   "VI" => "جزر فيرجن",
//   "VG" => "جزر فيرجن البريطانية",
//   "KY" => "جزر كايمان",
//   "CK" => "جزر كوك",
//   "CC" => "جزر كوكوس (كيلينغ)",
//   "MH" => "جزر مارشال",
//   "MP" => "جزر ماريانا الشمالية",
//   "IM" => "جزيرة آيل أوف مان",
//   "BV" => "جزيرة بوفيت",
//   "CX" => "جزيرة كريسماس",
//   "YT" => "جزيرة مايوت",
//   "NF" => "جزيرة نورفولك",
//   "HM" => "جزيرة هيرد وجزر ماكدونالد",
//   "CF" => "جمهورية أفريقيا الوسطى",
//   "DO" => "جمهورية الدومينيكان",
//   "CG" => "جمهورية الكونغو",
//   "CD" => "جمهورية الكونغو الديمقراطية",
//   "ZA" => "جنوب أفريقيا",
//   "SS" => "جنوب السودان",
//   "GT" => "جواتيمالا",
//   "GP" => "جواديلوب",
//   "GU" => "جوام",
//   "GE" => "جورجيا",
//   "GS" => "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
//   "GF" => "جيانا الفرنسية",
//   "DJ" => "جيبوتي",
//   "JE" => "جيرسي",
//   "GG" => "جيرنسي",
//   "DM" => "دومينيكا",
//   "RW" => "رواندا",
//   "BY" => "روسيا البيضاء",
//   "RO" => "رومانيا",
//   "RE" => "رينيون",
//   "ZM" => "زامبيا",
//   "ZW" => "زيمبابوي",
//   "WS" => "ساموا",
//   "AS" => "ساموا الأمريكية",
//   "PM" => "سان بيار وميكلون",
//   "SM" => "سان مارينو",
//   "BL" => "سانت بارتيليمي",
//   "ST" => "سانت تومي وبرينسبل",
//   "VC" => "سانت فنسنت وغرينادين",
//   "KN" => "سانت كيتس ونيفيس",
//   "LC" => "سانت لوسيا",
//   "MF" => "سانت مارتن",
//   "SH" => "سانت هيلانة",
//   "LK" => "سريلانكا",
//   "SJ" => "سفالبارد",
//   "OM" => "سلطنة عمان",
//   "SK" => "سلوفاكيا",
//   "SI" => "سلوفينيا",
//   "SG" => "سنغافورة",
//   "SZ" => "سوازيلاند",
//   "SY" => "سوريا",
//   "SR" => "سورينام",
//   "CH" => "سويسرا",
//   "SL" => "سيراليون",
//   "SC" => "سيشيل",
//   "SX" => "سينت مارتن",
//   "RS" => "صربيا",
//   "TJ" => "طاجيكستان",
//   "GH" => "غانا",
//   "GY" => "غيانا",
//   "GN" => "غينيا",
//   "GQ" => "غينيا الاستوائية",
//   "GW" => "غينيا بيساو",
//   "VU" => "فانواتو",
//   "FR" => "فرنسا",
//   "PS" => "فلسطين",
//   "VE" => "فنزويلا",
//   "FI" => "فنلندا",
//   "VN" => "فيتنام",
//   "FJ" => "فيجي",
//   "CY" => "قبرص",
//   "QA" => "قطر",
//   "KG" => "قيرغيزستان",
//   "KZ" => "كازاخستان",
//   "NC" => "كاليدونيا الجديدة",
//   "HR" => "كرواتيا",
//   "KH" => "كمبوديا",
//   "CA" => "كندا",
//   "CI" => "كوت ديفوار",
//   "CW" => "كوراكاو",
//   "KR" => "كوريا الجنوبية",
//   "KP" => "كوريا الشمالية",
//   "CR" => "كوستاريكا",
//   "KV" => "كوسوفو",
//   "CO" => "كولومبيا",
//   "KI" => "كيريباتي",
//   "KE" => "كينيا",
//   "LV" => "لاتفيا",
//   "LA" => "لاوس",
//   "LB" => "لبنان",
//   "LU" => "لوكسمبورغ",
//   "LR" => "ليبيريا",
//   "LT" => "ليتوانيا",
//   "LI" => "ليختنشتاين",
//   "LS" => "ليسوتو",
//   "MO" => "ماكاو",
//   "MW" => "مالاوي",
//   "MT" => "مالطا",
//   "ML" => "مالي",
//   "MY" => "ماليزيا",
//   "MG" => "مدغشقر",
//   "EG" => "مصر",
//   "MA" => "مغربي",
//   "MK" => "مقدونيا",
//   "MN" => "منغوليا",
//   "MR" => "موريتانيا",
//   "MU" => "موريشيوس",
//   "MZ" => "موزمبيق",
//   "MD" => "مولدوفيا",
//   "MC" => "موناكو",
//   "MS" => "مونتسيرات",
//   "NA" => "ناميبيا",
//   "NR" => "ناورو",
//   "NP" => "نيبال",
//   "NG" => "نيجيريا",
//   "NI" => "نيكاراغوا",
//   "NZ" => "نيوزيلندا",
//   "NU" => "نيوي",
//   "HT" => "هايتي",
//   "HN" => "هندوراس",
//   "NL" => "هولندا",
//   "HK" => "هونج كونج",
//   "WF" => "واليس وفوتونا",
//   "FM" => "ولايات ميكرونيزيا الموحدة"
//     ];
    // foreach ($latinCountries as $lc) {
    //   echo "['e_name'=>'".$lc['e_name']."', 'code'=>'".$lc['code']."', 'iso'=>'".$lc['iso']."',";
    //   foreach($countries as $code => $a_name) {
    //     if ($lc['iso'] == $code) {
    //       echo "'a_name'=>'".$a_name."'";
    //     }
    //   } echo "], ";
    // }
    return [['e_name'=>'Afghanistan', 'code'=>'93', 'iso'=>'AF','a_name'=>'أفغانستان'], ['e_name'=>'Albania', 'code'=>'355', 'iso'=>'AL','a_name'=>'ألبانيا'], ['e_name'=>'Algeria', 'code'=>'213', 'iso'=>'DZ','a_name'=>'الجزائر'], ['e_name'=>'American Samoa', 'code'=>'1-684', 'iso'=>'AS','a_name'=>'ساموا الأمريكية'], ['e_name'=>'Andorra', 'code'=>'376', 'iso'=>'AD','a_name'=>'أندورا'], ['e_name'=>'Angola', 'code'=>'244', 'iso'=>'AO','a_name'=>'أنجولا'], ['e_name'=>'Anguilla', 'code'=>'1-264', 'iso'=>'AI','a_name'=>'أنغيلا'], ['e_name'=>'Antarctica', 'code'=>'672', 'iso'=>'AQ','a_name'=>'القارة القطبية الجنوبية'], ['e_name'=>'Antigua and Barbuda', 'code'=>'1-268', 'iso'=>'AG','a_name'=>'انتيغوا وبربودا'], ['e_name'=>'Argentina', 'code'=>'54', 'iso'=>'AR','a_name'=>'الأرجنتين'], ['e_name'=>'Armenia', 'code'=>'374', 'iso'=>'AM','a_name'=>'أرمينيا'], ['e_name'=>'Aruba', 'code'=>'297', 'iso'=>'AW','a_name'=>'أروبا'], ['e_name'=>'Australia', 'code'=>'61', 'iso'=>'AU','a_name'=>'أستراليا'], ['e_name'=>'Austria', 'code'=>'43', 'iso'=>'AT','a_name'=>'النمسا'], ['e_name'=>'Azerbaijan', 'code'=>'994', 'iso'=>'AZ','a_name'=>'أذربيجان'], ['e_name'=>'Bahamas', 'code'=>'1-242', 'iso'=>'BS','a_name'=>'جزر البهاما'], ['e_name'=>'Bahrain', 'code'=>'973', 'iso'=>'BH','a_name'=>'البحرين'], ['e_name'=>'Bangladesh', 'code'=>'880', 'iso'=>'BD','a_name'=>'بنغلاديش'], ['e_name'=>'Barbados', 'code'=>'1-246', 'iso'=>'BB','a_name'=>'بربادوس'], ['e_name'=>'Belarus', 'code'=>'375', 'iso'=>'BY','a_name'=>'روسيا البيضاء'], ['e_name'=>'Belgium', 'code'=>'32', 'iso'=>'BE','a_name'=>'بلجيكا'], ['e_name'=>'Belize', 'code'=>'501', 'iso'=>'BZ','a_name'=>'بليز'], ['e_name'=>'Benin', 'code'=>'229', 'iso'=>'BJ','a_name'=>'بنين'], ['e_name'=>'Bermuda', 'code'=>'1-441', 'iso'=>'BM','a_name'=>'برمودا'], ['e_name'=>'Bhutan', 'code'=>'975', 'iso'=>'BT','a_name'=>'بوتان'], ['e_name'=>'Bolivia', 'code'=>'591', 'iso'=>'BO','a_name'=>'بوليفيا'], ['e_name'=>'Bosnia and Herzegovina', 'code'=>'387', 'iso'=>'BA','a_name'=>'البوسنة والهرسك'], ['e_name'=>'Botswana', 'code'=>'267', 'iso'=>'BW','a_name'=>'بوتسوانا'], ['e_name'=>'Brazil', 'code'=>'55', 'iso'=>'BR','a_name'=>'البرازيل'], ['e_name'=>'British Indian Ocean Territory', 'code'=>'246', 'iso'=>'IO','a_name'=>'إقليم المحيط الهندي البريطاني'], ['e_name'=>'British Virgin Islands', 'code'=>'1-284', 'iso'=>'VG','a_name'=>'جزر فيرجن البريطانية'], ['e_name'=>'Brunei', 'code'=>'673', 'iso'=>'BN','a_name'=>'بروناي دار السلام'], ['e_name'=>'Bulgaria', 'code'=>'359', 'iso'=>'BG','a_name'=>'بلغاريا'], ['e_name'=>'Burkina Faso', 'code'=>'226', 'iso'=>'BF','a_name'=>'بوركينا فاسو'], ['e_name'=>'Burundi', 'code'=>'257', 'iso'=>'BI','a_name'=>'بوروندي'], ['e_name'=>'Cambodia', 'code'=>'855', 'iso'=>'KH','a_name'=>'كمبوديا'], ['e_name'=>'Cameroon', 'code'=>'237', 'iso'=>'CM','a_name'=>'الكاميرون'], ['e_name'=>'Canada', 'code'=>'1', 'iso'=>'CA','a_name'=>'كندا'], ['e_name'=>'Cape Verde', 'code'=>'238', 'iso'=>'CV','a_name'=>'الرأس الأخضر'], ['e_name'=>'Cayman Islands', 'code'=>'1-345', 'iso'=>'KY','a_name'=>'جزر كايمان'], ['e_name'=>'Central African Republic', 'code'=>'236', 'iso'=>'CF','a_name'=>'جمهورية أفريقيا الوسطى'], ['e_name'=>'Chad', 'code'=>'235', 'iso'=>'TD','a_name'=>'تشاد'], ['e_name'=>'Chile', 'code'=>'56', 'iso'=>'CL','a_name'=>'تشيلي'], ['e_name'=>'China', 'code'=>'86', 'iso'=>'CN','a_name'=>'الصين'], ['e_name'=>'Christmas Island', 'code'=>'61', 'iso'=>'CX','a_name'=>'جزيرة كريسماس'], ['e_name'=>'Cocos Islands', 'code'=>'61', 'iso'=>'CC','a_name'=>'جزر كوكوس (كيلينغ)'], ['e_name'=>'Colombia', 'code'=>'57', 'iso'=>'CO','a_name'=>'كولومبيا'], ['e_name'=>'Comoros', 'code'=>'269', 'iso'=>'KM','a_name'=>'جزر القمر'], ['e_name'=>'Cook Islands', 'code'=>'682', 'iso'=>'CK','a_name'=>'جزر كوك'], ['e_name'=>'Costa Rica', 'code'=>'506', 'iso'=>'CR','a_name'=>'كوستاريكا'], ['e_name'=>'Croatia', 'code'=>'385', 'iso'=>'HR','a_name'=>'كرواتيا'], ['e_name'=>'Cuba', 'code'=>'53', 'iso'=>'CU',], ['e_name'=>'Curacao', 'code'=>'599', 'iso'=>'CW','a_name'=>'كوراكاو'], ['e_name'=>'Cyprus', 'code'=>'357', 'iso'=>'CY','a_name'=>'قبرص'], ['e_name'=>'Czech Republic', 'code'=>'420', 'iso'=>'CZ','a_name'=>'الجمهورية التشيكية'], ['e_name'=>'Democratic Republic of the Congo', 'code'=>'243', 'iso'=>'CD','a_name'=>'جمهورية الكونغو الديمقراطية'], ['e_name'=>'Denmark', 'code'=>'45', 'iso'=>'DK','a_name'=>'الدنمرك'], ['e_name'=>'Djibouti', 'code'=>'253', 'iso'=>'DJ','a_name'=>'جيبوتي'], ['e_name'=>'Dominica', 'code'=>'1-767', 'iso'=>'DM','a_name'=>'دومينيكا'], ['e_name'=>'Dominican Republic', 'code'=>'1-809, 1-829, 1-849', 'iso'=>'DO','a_name'=>'جمهورية الدومينيكان'], ['e_name'=>'East Timor', 'code'=>'670', 'iso'=>'TL','a_name'=>'تيمور الشرقية'], ['e_name'=>'Ecuador', 'code'=>'593', 'iso'=>'EC','a_name'=>'الإكوادور'], ['e_name'=>'Egypt', 'code'=>'20', 'iso'=>'EG','a_name'=>'مصر'], ['e_name'=>'El Salvador', 'code'=>'503', 'iso'=>'SV','a_name'=>'السلفادور'], ['e_name'=>'Equatorial Guinea', 'code'=>'240', 'iso'=>'GQ','a_name'=>'غينيا الاستوائية'], ['e_name'=>'Eritrea', 'code'=>'291', 'iso'=>'ER','a_name'=>'إريتريا'], ['e_name'=>'Estonia', 'code'=>'372', 'iso'=>'EE','a_name'=>'استونيا'], ['e_name'=>'Ethiopia', 'code'=>'251', 'iso'=>'ET','a_name'=>'أثيوبيا'], ['e_name'=>'Falkland Islands', 'code'=>'500', 'iso'=>'FK','a_name'=>'جزر فوكلاند (مالفيناس)'], ['e_name'=>'Faroe Islands', 'code'=>'298', 'iso'=>'FO','a_name'=>'جزر فارو'], ['e_name'=>'Fiji', 'code'=>'679', 'iso'=>'FJ','a_name'=>'فيجي'], ['e_name'=>'Finland', 'code'=>'358', 'iso'=>'FI','a_name'=>'فنلندا'], ['e_name'=>'France', 'code'=>'33', 'iso'=>'FR','a_name'=>'فرنسا'], ['e_name'=>'French Polynesia', 'code'=>'689', 'iso'=>'PF','a_name'=>'بولينيزيا الفرنسية'], ['e_name'=>'Gabon', 'code'=>'241', 'iso'=>'GA','a_name'=>'الجابون'], ['e_name'=>'Gambia', 'code'=>'220', 'iso'=>'GM','a_name'=>'جامبيا'], ['e_name'=>'Georgia', 'code'=>'995', 'iso'=>'GE','a_name'=>'جورجيا'], ['e_name'=>'Germany', 'code'=>'49', 'iso'=>'DE','a_name'=>'ألمانيا'], ['e_name'=>'Ghana', 'code'=>'233', 'iso'=>'GH','a_name'=>'غانا'], ['e_name'=>'Gibraltar', 'code'=>'350', 'iso'=>'GI','a_name'=>'جبل طارق'], ['e_name'=>'Greece', 'code'=>'30', 'iso'=>'GR','a_name'=>'اليونان'], ['e_name'=>'Greenland', 'code'=>'299', 'iso'=>'GL','a_name'=>'جرينلند'], ['e_name'=>'Grenada', 'code'=>'1-473', 'iso'=>'GD','a_name'=>'جرينادا'], ['e_name'=>'Guam', 'code'=>'1-671', 'iso'=>'GU','a_name'=>'جوام'], ['e_name'=>'Guatemala', 'code'=>'502', 'iso'=>'GT','a_name'=>'جواتيمالا'], ['e_name'=>'Guernsey', 'code'=>'44-1481', 'iso'=>'GG','a_name'=>'جيرنسي'], ['e_name'=>'Guinea', 'code'=>'224', 'iso'=>'GN','a_name'=>'غينيا'], ['e_name'=>'Guinea-Bissau', 'code'=>'245', 'iso'=>'GW','a_name'=>'غينيا بيساو'], ['e_name'=>'Guyana', 'code'=>'592', 'iso'=>'GY','a_name'=>'غيانا'], ['e_name'=>'Haiti', 'code'=>'509', 'iso'=>'HT','a_name'=>'هايتي'], ['e_name'=>'Honduras', 'code'=>'504', 'iso'=>'HN','a_name'=>'هندوراس'], ['e_name'=>'Hong Kong', 'code'=>'852', 'iso'=>'HK','a_name'=>'هونج كونج'], ['e_name'=>'Hungary', 'code'=>'36', 'iso'=>'HU','a_name'=>'المجر'], ['e_name'=>'Iceland', 'code'=>'354', 'iso'=>'IS','a_name'=>'أيسلندا'], ['e_name'=>'India', 'code'=>'91', 'iso'=>'IN',], ['e_name'=>'Indonesia', 'code'=>'62', 'iso'=>'ID','a_name'=>'إندونيسيا'], ['e_name'=>'Iran', 'code'=>'98', 'iso'=>'IR','a_name'=>'إيران'], ['e_name'=>'Iraq', 'code'=>'964', 'iso'=>'IQ','a_name'=>'العراق'], ['e_name'=>'Ireland', 'code'=>'353', 'iso'=>'IE','a_name'=>'ايرلندا'], ['e_name'=>'Isle of Man', 'code'=>'44-1624', 'iso'=>'IM','a_name'=>'جزيرة آيل أوف مان'], ['e_name'=>'Israel', 'code'=>'972', 'iso'=>'IL',], ['e_name'=>'Italy', 'code'=>'39', 'iso'=>'IT','a_name'=>'إيطاليا'], ['e_name'=>'Ivory Coast', 'code'=>'225', 'iso'=>'CI','a_name'=>'كوت ديفوار'], ['e_name'=>'Jamaica', 'code'=>'1-876', 'iso'=>'JM','a_name'=>'جامايكا'], ['e_name'=>'Japan', 'code'=>'81', 'iso'=>'JP','a_name'=>'اليابان'], ['e_name'=>'Jersey', 'code'=>'44-1534', 'iso'=>'JE','a_name'=>'جيرسي'], ['e_name'=>'Jordan', 'code'=>'962', 'iso'=>'JO','a_name'=>'الأردن'], ['e_name'=>'Kazakhstan', 'code'=>'7', 'iso'=>'KZ','a_name'=>'كازاخستان'], ['e_name'=>'Kenya', 'code'=>'254', 'iso'=>'KE','a_name'=>'كينيا'], ['e_name'=>'Kiribati', 'code'=>'686', 'iso'=>'KI','a_name'=>'كيريباتي'], ['e_name'=>'Kosovo', 'code'=>'383', 'iso'=>'XK',], ['e_name'=>'Kuwait', 'code'=>'965', 'iso'=>'KW','a_name'=>'الكويت'], ['e_name'=>'Kyrgyzstan', 'code'=>'996', 'iso'=>'KG','a_name'=>'قيرغيزستان'], ['e_name'=>'Laos', 'code'=>'856', 'iso'=>'LA','a_name'=>'لاوس'], ['e_name'=>'Latvia', 'code'=>'371', 'iso'=>'LV','a_name'=>'لاتفيا'], ['e_name'=>'Lebanon', 'code'=>'961', 'iso'=>'LB','a_name'=>'لبنان'], ['e_name'=>'Lesotho', 'code'=>'266', 'iso'=>'LS','a_name'=>'ليسوتو'], ['e_name'=>'Liberia', 'code'=>'231', 'iso'=>'LR','a_name'=>'ليبيريا'], ['e_name'=>'Libya', 'code'=>'218', 'iso'=>'LY',], ['e_name'=>'Liechtenstein', 'code'=>'423', 'iso'=>'LI','a_name'=>'ليختنشتاين'], ['e_name'=>'Lithuania', 'code'=>'370', 'iso'=>'LT','a_name'=>'ليتوانيا'], ['e_name'=>'Luxembourg', 'code'=>'352', 'iso'=>'LU','a_name'=>'لوكسمبورغ'], ['e_name'=>'Macao', 'code'=>'853', 'iso'=>'MO','a_name'=>'ماكاو'], ['e_name'=>'Macedonia', 'code'=>'389', 'iso'=>'MK','a_name'=>'مقدونيا'], ['e_name'=>'Madagascar', 'code'=>'261', 'iso'=>'MG','a_name'=>'مدغشقر'], ['e_name'=>'Malawi', 'code'=>'265', 'iso'=>'MW','a_name'=>'مالاوي'], ['e_name'=>'Malaysia', 'code'=>'60', 'iso'=>'MY','a_name'=>'ماليزيا'], ['e_name'=>'Maldives', 'code'=>'960', 'iso'=>'MV','a_name'=>'جزر المالديف'], ['e_name'=>'Mali', 'code'=>'223', 'iso'=>'ML','a_name'=>'مالي'], ['e_name'=>'Malta', 'code'=>'356', 'iso'=>'MT','a_name'=>'مالطا'], ['e_name'=>'Marshall Islands', 'code'=>'692', 'iso'=>'MH','a_name'=>'جزر مارشال'], ['e_name'=>'Mauritania', 'code'=>'222', 'iso'=>'MR','a_name'=>'موريتانيا'], ['e_name'=>'Mauritius', 'code'=>'230', 'iso'=>'MU','a_name'=>'موريشيوس'], ['e_name'=>'Mayotte', 'code'=>'262', 'iso'=>'YT','a_name'=>'جزيرة مايوت'], ['e_name'=>'Mexico', 'code'=>'52', 'iso'=>'MX','a_name'=>'المكسيك'], ['e_name'=>'Micronesia', 'code'=>'691', 'iso'=>'FM','a_name'=>'ولايات ميكرونيزيا الموحدة'], ['e_name'=>'Moldova', 'code'=>'373', 'iso'=>'MD','a_name'=>'مولدوفيا'], ['e_name'=>'Monaco', 'code'=>'377', 'iso'=>'MC','a_name'=>'موناكو'], ['e_name'=>'Mongolia', 'code'=>'976', 'iso'=>'MN','a_name'=>'منغوليا'], ['e_name'=>'Montenegro', 'code'=>'382', 'iso'=>'ME','a_name'=>'الجبل الأسود'], ['e_name'=>'Montserrat', 'code'=>'1-664', 'iso'=>'MS','a_name'=>'مونتسيرات'], ['e_name'=>'Morocco', 'code'=>'212', 'iso'=>'MA','a_name'=>'مغربي'], ['e_name'=>'Mozambique', 'code'=>'258', 'iso'=>'MZ','a_name'=>'موزمبيق'], ['e_name'=>'Myanmar', 'code'=>'95', 'iso'=>'MM','a_name'=>'بورما'], ['e_name'=>'Namibia', 'code'=>'264', 'iso'=>'NA','a_name'=>'ناميبيا'], ['e_name'=>'Nauru', 'code'=>'674', 'iso'=>'NR','a_name'=>'ناورو'], ['e_name'=>'Nepal', 'code'=>'977', 'iso'=>'NP','a_name'=>'نيبال'], ['e_name'=>'Netherlands', 'code'=>'31', 'iso'=>'NL','a_name'=>'هولندا'], ['e_name'=>'Netherlands Antilles', 'code'=>'599', 'iso'=>'AN','a_name'=>'جزر الانتيل الهولندية'], ['e_name'=>'New Caledonia', 'code'=>'687', 'iso'=>'NC','a_name'=>'كاليدونيا الجديدة'], ['e_name'=>'New Zealand', 'code'=>'64', 'iso'=>'NZ','a_name'=>'نيوزيلندا'], ['e_name'=>'Nicaragua', 'code'=>'505', 'iso'=>'NI','a_name'=>'نيكاراغوا'], ['e_name'=>'Niger', 'code'=>'227', 'iso'=>'NE','a_name'=>'النيجر'], ['e_name'=>'Nigeria', 'code'=>'234', 'iso'=>'NG','a_name'=>'نيجيريا'], ['e_name'=>'Niue', 'code'=>'683', 'iso'=>'NU','a_name'=>'نيوي'], ['e_name'=>'North Korea', 'code'=>'850', 'iso'=>'KP','a_name'=>'كوريا الشمالية'], ['e_name'=>'Northern Mariana Islands', 'code'=>'1-670', 'iso'=>'MP','a_name'=>'جزر ماريانا الشمالية'], ['e_name'=>'Norway', 'code'=>'47', 'iso'=>'NO','a_name'=>'النرويج'], ['e_name'=>'Oman', 'code'=>'968', 'iso'=>'OM','a_name'=>'سلطنة عمان'], ['e_name'=>'Pakistan', 'code'=>'92', 'iso'=>'PK','a_name'=>'باكستان'], ['e_name'=>'Palau', 'code'=>'680', 'iso'=>'PW','a_name'=>'بالاو'], ['e_name'=>'Palestine', 'code'=>'970', 'iso'=>'PS','a_name'=>'فلسطين'], ['e_name'=>'Panama', 'code'=>'507', 'iso'=>'PA','a_name'=>'بنما'], ['e_name'=>'Papua New Guinea', 'code'=>'675', 'iso'=>'PG','a_name'=>'بابوا غينيا الجديدة'], ['e_name'=>'Paraguay', 'code'=>'595', 'iso'=>'PY','a_name'=>'باراغواي'], ['e_name'=>'Peru', 'code'=>'51', 'iso'=>'PE','a_name'=>'بيرو'], ['e_name'=>'Philippines', 'code'=>'63', 'iso'=>'PH','a_name'=>'الفلبين'], ['e_name'=>'Pitcairn', 'code'=>'64', 'iso'=>'PN','a_name'=>'جزر بيتكيرن'], ['e_name'=>'Poland', 'code'=>'48', 'iso'=>'PL','a_name'=>'بولندا'], ['e_name'=>'Portugal', 'code'=>'351', 'iso'=>'PT','a_name'=>'البرتغال'], ['e_name'=>'Puerto Rico', 'code'=>'1-787, 1-939', 'iso'=>'PR','a_name'=>'بويرتو ريكو'], ['e_name'=>'Qatar', 'code'=>'974', 'iso'=>'QA','a_name'=>'قطر'], ['e_name'=>'Republic of the Congo', 'code'=>'242', 'iso'=>'CG','a_name'=>'جمهورية الكونغو'], ['e_name'=>'Reunion', 'code'=>'262', 'iso'=>'RE','a_name'=>'رينيون'], ['e_name'=>'Romania', 'code'=>'40', 'iso'=>'RO','a_name'=>'رومانيا'], ['e_name'=>'Russia', 'code'=>'7', 'iso'=>'RU','a_name'=>'الاتحاد الروسي'], ['e_name'=>'Rwanda', 'code'=>'250', 'iso'=>'RW','a_name'=>'رواندا'], ['e_name'=>'Saint Barthelemy', 'code'=>'590', 'iso'=>'BL','a_name'=>'سانت بارتيليمي'], ['e_name'=>'Saint Helena', 'code'=>'290', 'iso'=>'SH','a_name'=>'سانت هيلانة'], ['e_name'=>'Saint Kitts and Nevis', 'code'=>'1-869', 'iso'=>'KN','a_name'=>'سانت كيتس ونيفيس'], ['e_name'=>'Saint Lucia', 'code'=>'1-758', 'iso'=>'LC','a_name'=>'سانت لوسيا'], ['e_name'=>'Saint Martin', 'code'=>'590', 'iso'=>'MF','a_name'=>'سانت مارتن'], ['e_name'=>'Saint Pierre and Miquelon', 'code'=>'508', 'iso'=>'PM','a_name'=>'سان بيار وميكلون'], ['e_name'=>'Saint Vincent and the Grenadines', 'code'=>'1-784', 'iso'=>'VC','a_name'=>'سانت فنسنت وغرينادين'], ['e_name'=>'Samoa', 'code'=>'685', 'iso'=>'WS','a_name'=>'ساموا'], ['e_name'=>'San Marino', 'code'=>'378', 'iso'=>'SM','a_name'=>'سان مارينو'], ['e_name'=>'Sao Tome and Principe', 'code'=>'239', 'iso'=>'ST','a_name'=>'سانت تومي وبرينسبل'], ['e_name'=>'Saudi Arabia', 'code'=>'966', 'iso'=>'SA','a_name'=>'المملكة العربية السعودية'], ['e_name'=>'Senegal', 'code'=>'221', 'iso'=>'SN','a_name'=>'السنغال'], ['e_name'=>'Serbia', 'code'=>'381', 'iso'=>'RS','a_name'=>'صربيا'], ['e_name'=>'Seychelles', 'code'=>'248', 'iso'=>'SC','a_name'=>'سيشيل'], ['e_name'=>'Sierra Leone', 'code'=>'232', 'iso'=>'SL','a_name'=>'سيراليون'], ['e_name'=>'Singapore', 'code'=>'65', 'iso'=>'SG','a_name'=>'سنغافورة'], ['e_name'=>'Sint Maarten', 'code'=>'1-721', 'iso'=>'SX','a_name'=>'سينت مارتن'], ['e_name'=>'Slovakia', 'code'=>'421', 'iso'=>'SK','a_name'=>'سلوفاكيا'], ['e_name'=>'Slovenia', 'code'=>'386', 'iso'=>'SI','a_name'=>'سلوفينيا'], ['e_name'=>'Solomon Islands', 'code'=>'677', 'iso'=>'SB','a_name'=>'جزر سليمان'], ['e_name'=>'Somalia', 'code'=>'252', 'iso'=>'SO','a_name'=>'الصومال'], ['e_name'=>'South Africa', 'code'=>'27', 'iso'=>'ZA','a_name'=>'جنوب أفريقيا'], ['e_name'=>'South Korea', 'code'=>'82', 'iso'=>'KR','a_name'=>'كوريا الجنوبية'], ['e_name'=>'South Sudan', 'code'=>'211', 'iso'=>'SS','a_name'=>'جنوب السودان'], ['e_name'=>'Spain', 'code'=>'34', 'iso'=>'ES','a_name'=>'إسبانيا'], ['e_name'=>'Sri Lanka', 'code'=>'94', 'iso'=>'LK','a_name'=>'سريلانكا'], ['e_name'=>'Sudan', 'code'=>'249', 'iso'=>'SD','a_name'=>'السودان'], ['e_name'=>'Suriname', 'code'=>'597', 'iso'=>'SR','a_name'=>'سورينام'], ['e_name'=>'Svalbard and Jan Mayen', 'code'=>'47', 'iso'=>'SJ','a_name'=>'سفالبارد'], ['e_name'=>'Swaziland', 'code'=>'268', 'iso'=>'SZ','a_name'=>'سوازيلاند'], ['e_name'=>'Sweden', 'code'=>'46', 'iso'=>'SE','a_name'=>'السويد'], ['e_name'=>'Switzerland', 'code'=>'41', 'iso'=>'CH','a_name'=>'سويسرا'], ['e_name'=>'Syria', 'code'=>'963', 'iso'=>'SY','a_name'=>'سوريا'], ['e_name'=>'Taiwan', 'code'=>'886', 'iso'=>'TW','a_name'=>'تايوان'], ['e_name'=>'Tajikistan', 'code'=>'992', 'iso'=>'TJ','a_name'=>'طاجيكستان'], ['e_name'=>'Tanzania', 'code'=>'255', 'iso'=>'TZ','a_name'=>'تنزانيا'], ['e_name'=>'Thailand', 'code'=>'66', 'iso'=>'TH','a_name'=>'تايلاند'], ['e_name'=>'Togo', 'code'=>'228', 'iso'=>'TG','a_name'=>'توجو'], ['e_name'=>'Tokelau', 'code'=>'690', 'iso'=>'TK','a_name'=>'توكيلاو'], ['e_name'=>'Tonga', 'code'=>'676', 'iso'=>'TO','a_name'=>'تونجا'], ['e_name'=>'Trinidad and Tobago', 'code'=>'1-868', 'iso'=>'TT','a_name'=>'ترينيداد وتوباجو'], ['e_name'=>'Tunisia', 'code'=>'216', 'iso'=>'TN','a_name'=>'تونس'], ['e_name'=>'Turkey', 'code'=>'90', 'iso'=>'TR','a_name'=>'تركيا'], ['e_name'=>'Turkmenistan', 'code'=>'993', 'iso'=>'TM','a_name'=>'تركمانستان'], ['e_name'=>'Turks and Caicos Islands', 'code'=>'1-649', 'iso'=>'TC','a_name'=>'جزر تركس وكايكوس'], ['e_name'=>'Tuvalu', 'code'=>'688', 'iso'=>'TV','a_name'=>'توفالو'], ['e_name'=>'U.S. Virgin Islands', 'code'=>'1-340', 'iso'=>'VI','a_name'=>'جزر فيرجن'], ['e_name'=>'Uganda', 'code'=>'256', 'iso'=>'UG','a_name'=>'أوغندا'], ['e_name'=>'Ukraine', 'code'=>'380', 'iso'=>'UA','a_name'=>'أوكرانيا'], ['e_name'=>'United Arab Emirates', 'code'=>'971', 'iso'=>'AE','a_name'=>'الإمارات العربية المتحدة'], ['e_name'=>'United Kingdom', 'code'=>'44', 'iso'=>'GB',], ['e_name'=>'United States', 'code'=>'1', 'iso'=>'US',], ['e_name'=>'Uruguay', 'code'=>'598', 'iso'=>'UY','a_name'=>'أوروجواي'], ['e_name'=>'Uzbekistan', 'code'=>'998', 'iso'=>'UZ','a_name'=>'أوزبكستان'], ['e_name'=>'Vanuatu', 'code'=>'678', 'iso'=>'VU','a_name'=>'فانواتو'], ['e_name'=>'Vatican', 'code'=>'379', 'iso'=>'VA','a_name'=>'الكرسي الرسولي (الفاتيكان)'], ['e_name'=>'Venezuela', 'code'=>'58', 'iso'=>'VE','a_name'=>'فنزويلا'], ['e_name'=>'Vietnam', 'code'=>'84', 'iso'=>'VN','a_name'=>'فيتنام'], ['e_name'=>'Wallis and Futuna', 'code'=>'681', 'iso'=>'WF','a_name'=>'واليس وفوتونا'], ['e_name'=>'Western Sahara', 'code'=>'212', 'iso'=>'EH','a_name'=>'الصحراء الغربية'], ['e_name'=>'Yemen', 'code'=>'967', 'iso'=>'YE','a_name'=>'اليمن'], ['e_name'=>'Zambia', 'code'=>'260', 'iso'=>'ZM','a_name'=>'زامبيا'], ['e_name'=>'Zimbabwe', 'code'=>'263', 'iso'=>'ZW','a_name'=>'زيمبابوي']];
  }
}
